#!/usr/bin/env bash
# grok-env.sh <grok args...> — exec the SP-5 copy of grok 1.0.40 in a scrubbed env with the
# isolated HOME/GROK_HOME (no xAI credentials) and every phone-home switch off.
# Expects LITELLM_API_KEY in the caller's env (never printed); it is passed through only as
# the model's env_key and is excluded from the bash tool's env by config.toml.
set -u
GH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
exec env -i \
  HOME="$GH" GROK_HOME="$GH/.grok" \
  PATH="/usr/local/bin:/usr/bin:/bin" SHELL=/bin/bash USER="${USER:-bmt}" LOGNAME="${USER:-bmt}" \
  TERM=dumb LANG=C.UTF-8 LC_ALL=C.UTF-8 NO_COLOR=1 \
  LITELLM_API_KEY="${LITELLM_API_KEY:-}" \
  GROK_DEFAULT_MODEL=local-coder \
  GROK_DISABLE_AUTOUPDATER=1 \
  GROK_TELEMETRY_ENABLED=0 GROK_FEEDBACK_ENABLED=0 GROK_FEEDBACK_TRACE_CARD=0 \
  GROK_TELEMETRY_MIXPANEL_ENABLED=0 GROK_TELEMETRY_TRACE_UPLOAD=0 GROK_EXTERNAL_OTEL=0 \
  GROK_AGENT_DASHBOARD=0 GROK_CAMPAIGNS=0 GROK_MANAGED_MCPS_ENABLED=0 \
  GROK_MEMORY=0 GROK_SUBAGENTS=0 GROK_WEB_FETCH=0 GROK_BACKEND_SEARCH=0 \
  GROK_PROMPT_SUGGESTIONS=0 GROK_SESSION_RECAP=0 GROK_TURN_SUMMARY=0 GROK_TITLE_REFRESH=0 \
  GROK_VOICE_MODE=0 GROK_LSP_TOOLS=0 \
  GROK_CLAUDE_AGENTS_ENABLED=0 GROK_CLAUDE_HOOKS_ENABLED=0 GROK_CLAUDE_MCPS_ENABLED=0 \
  GROK_CLAUDE_RULES_ENABLED=0 GROK_CLAUDE_SKILLS_ENABLED=0 \
  GROK_CURSOR_AGENTS_ENABLED=0 GROK_CURSOR_HOOKS_ENABLED=0 GROK_CURSOR_MCPS_ENABLED=0 \
  GROK_CURSOR_RULES_ENABLED=0 GROK_CURSOR_SKILLS_ENABLED=0 \
  "$GH/bin/grok" "$@"
