/**
 * Forgetting one thing an agent remembers — S4.4 (D-041).
 *
 * There is no "delete this piece" anywhere below, and that is the design, not
 * a gap: D-035 measured Qdrant keeping the bytes of points deleted one at a
 * time. So forgetting is done the only way that removes bytes: the source file
 * goes from `memory/`, the subject's collection is dropped whole, and both
 * indexes are rebuilt from what is left. Then the needle is looked for again.
 *
 * Plan and commit are split, as in `erase` and `ingest`: {@link planForget}
 * reads and decides and writes nothing; {@link commitForget} takes the plan.
 */

import { readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import type { SubjectId } from "../types.ts";
import type { VectorEndpoints } from "./endpoints.ts";
import { buildFts, searchFts } from "./fts.ts";
import { IMPORTED_DIR } from "./ingest.ts";
import { readRagMarker, type RagMarker } from "./marker.ts";
import { MEMORY_DIR, readMemory } from "./sources.ts";
import { collectionState, dropCollection, type CollectionState, type Fetch } from "./store-admin.ts";
import { replaceCollection } from "./vector.ts";

/** What was asked to be forgotten. */
export type ForgetTarget =
  | { readonly kind: "files"; readonly files: readonly string[] }
  | { readonly kind: "match"; readonly text: string };

/** One file that will go, and where the needle was seen in it. */
export interface ForgetFile {
  readonly path: string;
  /** 1-based lines the needle is on; empty for a file named with `--file`. */
  readonly lines: readonly number[];
  /** True when `memory ingest` could bring it back. */
  readonly imported: boolean;
}

export interface ForgetPlan {
  readonly agentDir: string;
  readonly subject: SubjectId;
  readonly target: ForgetTarget;
  readonly files: readonly ForgetFile[];
  /** Where the collection is, if om-agi ever wrote one or one is configured; `null` if nowhere. */
  readonly qdrantUrl: string | null;
  readonly store: CollectionState | null;
  readonly refusals: readonly string[];
}

/**
 * Decide what goes. Writes nothing.
 *
 * `--file` paths must be under `memory/` and must exist. `--match` is a plain,
 * case-insensitive substring over every file `readMemory` reads — and only
 * those under `memory/`: the action summary is regenerated by `observe
 * actions --write`, so deleting it here would not forget anything.
 */
export async function planForget(options: {
  readonly agentDir: string;
  readonly subject: SubjectId;
  readonly target: ForgetTarget;
  readonly markerDir: string;
  readonly endpoints: VectorEndpoints | { readonly reason: string };
  readonly network?: Fetch;
}): Promise<ForgetPlan> {
  const { agentDir, subject, target } = options;
  const refusals: string[] = [];
  const files: ForgetFile[] = [];
  const imported = (path: string) => path.startsWith(`${MEMORY_DIR}/${IMPORTED_DIR}/`);

  if (target.kind === "files") {
    for (const raw of target.files) {
      const path = raw.replace(/^\.\//, "");
      if (!path.startsWith(`${MEMORY_DIR}/`) || path.split("/").includes("..")) {
        refusals.push(`${raw}: only a file under ${MEMORY_DIR}/ can be forgotten here`);
        continue;
      }
      if (!(await Bun.file(join(agentDir, path)).exists())) {
        refusals.push(`${raw}: not there`);
        continue;
      }
      files.push({ path, lines: [], imported: imported(path) });
    }
  } else {
    const needle = target.text.toLowerCase();
    if (needle.trim().length < 3) refusals.push("--match needs at least three characters; shorter would match nearly everything");
    else {
      for (const path of (await readMemory(agentDir)).files) {
        if (!path.startsWith(`${MEMORY_DIR}/`)) continue;
        const lines = (await readFile(join(agentDir, path), "utf8"))
          .split("\n")
          .flatMap((line, i) => (line.toLowerCase().includes(needle) ? [i + 1] : []));
        if (lines.length > 0) files.push({ path, lines, imported: imported(path) });
      }
    }
  }

  // The marker says where om-agi wrote; without one, the configured store is
  // still asked, because a collection may exist from before markers did.
  const marker: RagMarker | "unreadable" | null = await readRagMarker(options.markerDir);
  const qdrantUrl =
    marker !== null && marker !== "unreadable"
      ? marker.qdrantUrl
      : "reason" in options.endpoints
        ? null
        : options.endpoints.qdrantUrl;
  let store: CollectionState | null = null;
  if (marker === "unreadable") {
    refusals.push("the record of where vectors were written cannot be read, so the collection cannot be found to drop");
  } else if (qdrantUrl !== null) {
    store = await collectionState(qdrantUrl, subject, options.network);
    if (store.kind === "unreachable" && marker !== null) {
      refusals.push(
        `om-agi wrote vectors for this subject to ${qdrantUrl} and cannot reach it now (${store.reason}). ` +
          `Nothing was removed: forgetting the file and keeping its vectors would not be forgetting.`,
      );
    }
  }

  return { agentDir, subject, target, files, qdrantUrl, store, refusals };
}

export interface ForgetResult {
  readonly removed: readonly string[];
  readonly dropped: boolean | null;
  readonly fts: number;
  readonly vectors: { readonly ok: true; readonly points: number } | { readonly ok: false; readonly reason: string } | null;
  /** AC4 — every number here is read back after the fact. */
  readonly check: {
    readonly filesStillMatching: readonly string[];
    readonly ftsStillMatching: number;
    readonly pointsAfter: number | null;
    readonly piecesAfter: number;
    readonly passed: boolean;
  };
}

/** Carry out the plan: files, then the collection, then both indexes, then look again. */
export async function commitForget(
  plan: ForgetPlan,
  endpoints: VectorEndpoints | { readonly reason: string },
  network?: Fetch,
): Promise<ForgetResult> {
  if (plan.refusals.length > 0) throw new Error("a refused plan cannot be committed");
  for (const file of plan.files) await rm(join(plan.agentDir, file.path), { force: true });

  // The collection goes whole whether or not it can be rebuilt: forgetting
  // wins over recall (AC3).
  let dropped: boolean | null = null;
  if (plan.qdrantUrl !== null && plan.store?.kind === "present") {
    dropped = (await dropCollection(plan.qdrantUrl, plan.subject, network)).dropped;
  }

  const left = await readMemory(plan.agentDir);
  const fts = await buildFts(plan.agentDir, left.chunks);

  let vectors: ForgetResult["vectors"] = null;
  if (plan.store?.kind === "present" && dropped === true) {
    if ("reason" in endpoints) vectors = { ok: false, reason: endpoints.reason };
    else {
      try {
        vectors = { ok: true, points: await replaceCollection(endpoints, plan.subject, left.chunks, network) };
      } catch (cause) {
        vectors = { ok: false, reason: cause instanceof Error ? cause.message : String(cause) };
      }
    }
  }

  // AC4: look again, from disk and from the stores.
  const filesStillMatching: string[] = [];
  let ftsStillMatching = 0;
  if (plan.target.kind === "match") {
    const needle = plan.target.text.toLowerCase();
    for (const path of left.files) {
      if (!path.startsWith(`${MEMORY_DIR}/`)) continue;
      if ((await readFile(join(plan.agentDir, path), "utf8")).toLowerCase().includes(needle)) {
        filesStillMatching.push(path);
      }
    }
    ftsStillMatching = (await searchFts(plan.agentDir, plan.target.text, 1000)).length;
  }
  for (const file of plan.files) {
    if (await Bun.file(join(plan.agentDir, file.path)).exists()) filesStillMatching.push(file.path);
  }
  let pointsAfter: number | null = null;
  if (plan.qdrantUrl !== null && dropped !== null) {
    const after = await collectionState(plan.qdrantUrl, plan.subject, network);
    pointsAfter = after.kind === "present" ? after.points : after.kind === "absent" ? 0 : null;
  }
  const expectedPoints = vectors !== null && vectors.ok ? left.chunks.length : 0;
  const passed =
    filesStillMatching.length === 0 &&
    ftsStillMatching === 0 &&
    (dropped === null || (dropped && pointsAfter === expectedPoints));

  return {
    removed: plan.files.map((file) => file.path),
    dropped,
    fts,
    vectors,
    check: { filesStillMatching, ftsStillMatching, pointsAfter, piecesAfter: left.chunks.length, passed },
  };
}

/** The plan as lines. Never the text of a matched line. */
export function formatForgetPlan(plan: ForgetPlan): readonly string[] {
  const lines = [`  ${plan.files.length} file(s) would go`];
  for (const file of plan.files) {
    lines.push(
      `  - ${file.path}${file.lines.length > 0 ? `  (line ${file.lines.slice(0, 8).join(", ")}${file.lines.length > 8 ? ", …" : ""})` : ""}` +
        (file.imported ? "  ← imported: `memory ingest` brings it back while the source still has it" : ""),
    );
  }
  lines.push(
    plan.qdrantUrl === null
      ? "  vectors: no store to ask, and no record of writing one"
      : plan.store?.kind === "present"
        ? `  vectors: the collection at ${plan.qdrantUrl} (${plan.store.points} point(s)) is dropped whole, then rebuilt from what is left`
        : plan.store?.kind === "absent"
          ? `  vectors: no collection at ${plan.qdrantUrl}`
          : `  vectors: ${plan.qdrantUrl} did not answer`,
  );
  lines.push("  full-text: rebuilt from what is left");
  return lines;
}
