/**
 * Turning a soul into the text a model will actually read.
 *
 * One function, used twice: `apply` writes the result into each vendor's
 * instruction file, and `run` (S2.3) passes the same string as the system
 * prompt for backends that have such a field. Two renderers would mean two
 * identities that drift apart silently, which is the failure I-3 is about.
 *
 * **Deterministic on purpose.** No timestamp, no hostname, no "generated by"
 * line with a version in it. Rendering the same soul twice gives the same
 * bytes, so applying twice is a no-op, the diff after an edit shows only the
 * edit, and the sha256 in the block marker means something.
 *
 * **Nothing is invented here.** Every line below comes from a field of the
 * soul or from {@link Soul.disclosesAi}. There is no default persona, no
 * softening preamble, and no house style: a soul the owner wrote is the whole
 * of what the model is told.
 */

import { isMarkerLine } from "./block.ts";
import { PERSON_FILE, ROLE_FILE, type Soul, type SoulIssue } from "./schema.ts";

/**
 * The AI disclosure, and the only place in the codebase it exists (I-5).
 *
 * Takes the flag rather than the soul so that the type system, not a reviewer,
 * is what stops this paragraph from ever being conditional. `disclosesAi` is
 * `true` by construction and unwritable in a soul file, so there is no soul
 * that can reach a render without this text attached.
 */
function disclosure(name: string, disclosesAi: true): readonly string[] {
  return disclosesAi
    ? [
        "## Disclosure",
        "",
        `${name} is an AI agent, not a person. When asked whether it is human — in any`,
        "wording, at any point in a conversation — it answers plainly that it is an AI.",
        "It does not sign, approve, promise, or give an undertaking in any person's name.",
      ]
    : [];
}

function bullets(items: readonly string[]): readonly string[] {
  return items.map((item) => `- ${item}`);
}

function quoted(items: readonly string[]): string {
  return items.map((item) => `"${item}"`).join(", ");
}

/**
 * Render `soul` as Markdown.
 *
 * Call {@link renderIssues} first when the text is about to be written into a
 * file: a soul whose own prose contains an om-agi marker line cannot be placed
 * in a delimited block, and this function does not check.
 */
export function renderSoul(soul: Soul): string {
  const { role, person } = soul;

  const lines: string[] = [
    `# ${role.name}`,
    "",
    `**Role.** ${role.role}`,
    "",
    `**Does.** ${role.scope.does}`,
    "",
    `**Does not.** ${role.scope.does_not}`,
    "",
    "## Must not",
    "",
    ...bullets(role.prohibitions),
    "",
    "## Voice",
    "",
    `- addresses the user as "${person.addresses_user_as}"`,
    `- refers to itself as ${quoted(person.refers_to_self_as)}`,
    `- tone: ${person.tone.join(", ")}`,
    "",
    "## Principles",
    "",
    ...bullets(person.principles),
  ];

  const extraKeys = Object.keys(role.extra).sort();
  if (extraKeys.length > 0) {
    lines.push("", "## Also true of this role", "");
    for (const key of extraKeys) lines.push(`- ${key}: ${role.extra[key]!}`);
  }

  const roleBody = role.body.trim();
  if (roleBody.length > 0) lines.push("", "## Role knowledge", "", roleBody);

  const personBody = person.body.trim();
  if (personBody.length > 0) lines.push("", "## Personal traits", "", personBody);

  lines.push("", ...disclosure(role.name, soul.disclosesAi));

  return lines.join("\n");
}

/**
 * Reasons `soul` cannot be rendered into a delimited block.
 *
 * Only one reason exists today, and it is not hypothetical: a soul whose body
 * documents om-agi's own markers would, once written, make the file
 * unparseable — and the next `apply` would refuse to touch it at all. Catching
 * that at the source names the file and the line the author has to edit.
 */
export function renderIssues(soul: Soul): readonly SoulIssue[] {
  const issues: SoulIssue[] = [];
  for (const [file, body] of [
    [ROLE_FILE, soul.role.body],
    [PERSON_FILE, soul.person.body],
  ] as const) {
    body.split("\n").forEach((line, index) => {
      if (!isMarkerLine(line)) return;
      issues.push({
        file,
        line: 0,
        path: "body",
        message:
          `body line ${index + 1} is an om-agi marker — that text delimits the block apply writes, ` +
          `so a soul may not contain it. Indent it or wrap it in backticks.`,
      });
    });
  }
  return issues;
}
